import type { Metadata } from "next";
import { Klee_One } from "next/font/google";
import "../../styles/global.css";

const kleeOne = Klee_One({ weight: "600", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dango the World portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="jp">
      <body className={kleeOne.className}>{children}</body>
    </html>
  );
}
